In [4]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [5]:
data = {
    "Name": ["Anu", "Priya", "Kaviya", "Rahul", "Anu", "Vijay"],
    "Age": [21, 22, np.nan, 23, 21, 24],
    "Course": ["MCA", "MCA", "MBA", "MCA", "MCA", None],
    "Marks": [85, 90, 88, np.nan, 85, 78]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

     Name   Age Course  Marks
0     Anu  21.0    MCA   85.0
1   Priya  22.0    MCA   90.0
2  Kaviya   NaN    MBA   88.0
3   Rahul  23.0    MCA    NaN
4     Anu  21.0    MCA   85.0
5   Vijay  24.0    NaN   78.0

In [6]:
print("Dataset Information:")
df.info()

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     5 non-null      float64
 2   Course  5 non-null      str
 3   Marks   5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

Dataset Shape:
(6, 4)

Missing Values:
Name      0
Age       1
Course    1
Marks     1
dtype: int64

Duplicate Rows:
1

In [7]:
# Fill missing age with the average age
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Fill missing course with the most frequent course
df["Course"] = df["Course"].fillna(df["Course"].mode()[0])

# Fill missing marks with the average marks
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print("Missing Values Handled:")
display(df)

Missing Values Handled:

     Name   Age Course  Marks
0     Anu  21.0    MCA   85.0
1   Priya  22.0    MCA   90.0
2  Kaviya  22.2    MBA   88.0
3   Rahul  23.0    MCA   85.2
4     Anu  21.0    MCA   85.0
5   Vijay  24.0    MCA   78.0

In [8]:
df = df.drop_duplicates()

print("Dataset After Removing Duplicates:")
display(df)

print("Remaining Duplicate Rows:", df.duplicated().sum())

Dataset After Removing Duplicates:

     Name   Age Course  Marks
0     Anu  21.0    MCA   85.0
1   Priya  22.0    MCA   90.0
2  Kaviya  22.2    MBA   88.0
3   Rahul  23.0    MCA   85.2
5   Vijay  24.0    MCA   78.0

Remaining Duplicate Rows: 0

In [9]:
df["Age"] = df["Age"].round().astype(int)
df["Marks"] = df["Marks"].round(2)

print("Data Types After Correction:")
print(df.dtypes)

Data Types After Correction:
Name          str
Age         int64
Course        str
Marks     float64
dtype: object

In [10]:
print("Missing Values After Cleaning:")
print(df.isnull().sum())

print("\nDuplicate Rows After Cleaning:")
print(df.duplicated().sum())

print("\nFinal Cleaned Dataset:")
display(df)

Missing Values After Cleaning:
Name      0
Age       0
Course    0
Marks     0
dtype: int64

Duplicate Rows After Cleaning:
0

Final Cleaned Dataset:

     Name  Age Course  Marks
0     Anu   21    MCA   85.0
1   Priya   22    MCA   90.0
2  Kaviya   22    MBA   88.0
3   Rahul   23    MCA   85.2
5   Vijay   24    MCA   78.0

In [11]:
df.to_csv("cleaned_student_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!